
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const ROOT_DIR = path.resolve(__dirname, '..');
const VAULT_DIR = path.join(ROOT_DIR, 'data', 'ai-generated', 'vault');
const OUT_FILE = path.join(ROOT_DIR, 'data', 'vaultItems.ts');

console.log('Project Root:', ROOT_DIR);
console.log('Vault Dir:', VAULT_DIR);
console.log('Output File:', OUT_FILE);

async function main() {
    console.log('🔍 Scanning Vault for JSON items...');
    const items = [];

    async function scan(dir) {
        console.log(`📂 Entering: ${dir}`);
        try {
            const entries = await fs.promises.readdir(dir, { withFileTypes: true });
            for (const entry of entries) {
                const fullPath = path.join(dir, entry.name);
                if (entry.isDirectory()) {
                    await scan(fullPath);
                } else if (entry.isFile() && entry.name.endsWith('.json')) {
                    try {
                        const content = await fs.promises.readFile(fullPath, 'utf-8');
                        const json = JSON.parse(content);
                        const entriesToAdd = Array.isArray(json) ? json : [json];
                        for (const item of entriesToAdd) {
                            if (item.id && item.type) {
                                items.push(item);
                            }
                        }
                    } catch (e) {
                        console.error(`❌ Error parsing ${entry.name}:`, e.message);
                    }
                }
            }
        } catch (err) {
            console.error(`❌ Error reading dir ${dir}:`, err.message);
        }
    }

    if (fs.existsSync(VAULT_DIR)) {
        await scan(VAULT_DIR);
    } else {
        console.error(`❌ Vault directory does not exist: ${VAULT_DIR}`);
        return;
    }

    const fileContent = `// Auto-generated by scripts/generateVaultIndex.js
// Do not edit manually.
import { MasterItem } from '../types/master';

export const VAULT_ITEMS: MasterItem[] = ${JSON.stringify(items, null, 4)};
`;

    fs.writeFileSync(OUT_FILE, fileContent);
    console.log(`✅ Successfully indexed ${items.length} items to ${OUT_FILE}`);
}

main().catch(console.error);
