import fs from 'fs/promises';
import path from 'path';

const VAULT_DIR = path.resolve('data/ai-generated/vault');
const OUT_FILE = path.resolve('data/vaultItems.ts');

async function main() {
    console.log('🔍 Scanning Vault for JSON items...');
    const items: any[] = [];

    async function scan(dir: string) {
        const entries = await fs.readdir(dir, { withFileTypes: true });
        for (const entry of entries) {
            const fullPath = path.join(dir, entry.name);
            if (entry.isDirectory()) {
                await scan(fullPath);
            } else if (entry.isFile() && entry.name.endsWith('.json')) {
                try {
                    const content = await fs.readFile(fullPath, 'utf-8');
                    const json = JSON.parse(content);
                    if (Array.isArray(json)) {
                        items.push(...json);
                    } else if (typeof json === 'object' && json !== null) {
                        items.push(json);
                    }
                } catch (e) {
                    console.error(`❌ Error parsing ${entry.name}:`, e);
                }
            }
        }
    }

    await scan(VAULT_DIR);

    const fileContent = `// Auto-generated by scripts/generateVaultIndex.ts
// Do not edit manually.
import { MasterItem } from '../types/master';

export const VAULT_ITEMS: MasterItem[] = ${JSON.stringify(items, null, 4)};
`;

    await fs.writeFile(OUT_FILE, fileContent);
    console.log(`✅ Successfully indexed ${items.length} items to ${OUT_FILE}`);
}

main().catch(console.error);
